### ISSUE TITLE
Centrimo Error

### ISSUE THREAD

**Issue by uerdogdu** [hoffmangroup/peako#2]
Hello,

I got an error while running the pipeline at centrimo stage:

Traceback (most recent call last):
  File "/home/erdogdu/localenv/miniconda3/envs/peako/lib/python3.7/site-packages/peako/data/add-pooled-de-novo-motifs-**centrimo.py", line 118, in <module>
    cmd.insert(cmd.index(list(filter(db_regex.match, cmd))[0]), i)
IndexError: list index out of range**
[Sun Feb 13 18:29:39 2022]
Error in rule add_de_novo_motifs:
    jobid: 7
    output: commands-pooled-de-novo.sh
    shell:

Could you help me?

I have meme installed in my environment. Should I nevertheless change to centrimo binaries you have provided?

Thanks in advance,

Umut

**Comment by cviner** [comment]
This is likely due to having an older version of the MEME Suite installed.

Use of the CentriMo binary we provide should indeed resolve this. You may have to first delete the prior MEME Suite runs, if retained, or otherwise ensure that portion of the pipeline is re-run using the new binary. 

If that doesn't work, could you please provide your MEME Suite version, so we can debug this further?

Thanks for using peaKO!

**Comment by cviner** [comment]
I should just add that it might be a good idea to first check that the MEME Suite ran correctly or had any upstream errors, e.g., running DREME.

Hopefully your version of the MEME Suite is >= 4.12.0. If not, I'd suggest instead installing a more recent version, ideally [version 5.1.1](https://meme-suite.org/meme/meme-software/5.1.1/meme-5.1.1.tar.gz), ensuring to also download the motif databases, per the [installation instructions](https://meme-suite.org/meme/doc/install.html?man_type=web).

**Comment by cviner** [comment]
I'm going to assume that you've resolved or abandoned this, but please do feel free to re-open this if you need any further assistance!
